### ISSUE TITLE
Which UI component library should we use?

### ISSUE THREAD

**Issue by sbose78** [che-electron/client#32]
Patternfly or something Che-specific?

**Comment by benoitf** [comment]
@slemeur ?

**Comment by slemeur** [comment]
Go with the UI from Che dashboard.
I don't think we should be introducing a new UI/look&feel for that client.

**Comment by waveywaves** [comment]
We should be following the Che Color Schemes and Design ... @jthvjn What do you think ?

**Comment by jthvjn** [comment]
https://material.angular.io/

![screenshot from 2018-10-09 12-36-15](https://user-images.githubusercontent.com/15844451/46652204-0605c180-cbc0-11e8-94f2-e21dd6715c2f.png)

**Comment by waveywaves** [comment]
We will have to use something Che Specific only. Most propbably will pick up CSS form the Che Repo.

**Comment by waveywaves** [comment]
As we have found the answer to this (i.e. Pick up CSS from the Che Frontend), we are closing this issue.
