### ISSUE TITLE
Starting/Launching the workspaces

### ISSUE THREAD

**Issue by jthvjn** [che-electron/client#47]
Concern: Starting the workspace (Not running ones) just on clicking the workspace item  -> Since items in the screen are small enough -> wrong/multiple workspace can be clicked -> starting and running a workspace costs resources -> unwanted costs.

From UX and functionality perspective, how should this be dealt?

**Comment by jthvjn** [comment]
On clicking, if workspace is in ‘Stopped state’, introduce a secondary confirmation to start it as an alert. Available in Web-based Che.

**Comment by jthvjn** [comment]
> Concern: Starting the workspace (Not running ones) just on clicking the workspace item -> Since items in the screen are small enough -> wrong/multiple workspace can be clicked -> starting and running a workspace costs resources -> unwanted costs.

On clicking, if workspace is in ‘Stopped state’, introduce a secondary confirmation to start it as an alert. Available in Web-based Che.

**Comment by debsmita1** [comment]
Fixed the issue in this PR : #50
