### ISSUE TITLE
Dynamically update workspace dashboard

### ISSUE THREAD

**Issue by waveywaves** [che-electron/client#7]
The Workspace Watcher would be a daemon kind of process running the background which would be watching the Workspaces to reflect metadata of the workspaces which would tend to change. 
The implementation would have to be done with the combination of React and Socket.io as it would be better than just simple polling.

**Comment by sbose78** [comment]
@waveywaves Create sub-tasks please.

**Comment by waveywaves** [comment]
Redux would be managing this and in case if we need any kind of polling mechanism or any kind of observables we can look into this later. Closing this for now.
